export enum NotificationType {
    MATCH_INVITE  = "MATCH_INVITE", 
    MATCH_STARTED  = "MATCH_STARTED",  
    MATCH_ENDED = "MATCH_ENDED", 
    SUBMISSION_RECEIVED = "SUBMISSION_RECEIVED", 
    SUBMISSION_RESULT = "SUBMISSION_RESULT", 
    OPPONENT_RESIGNED = "OPPONENT_RESIGNED", 
    FRIEND_REQUEST = "FRIEND_REQUEST", 
    FRIEND_ACCEPTED = "FRIEND_ACCEPTED"
}
  