export enum NotificationType {
    MATCH_INVITATION  = "MATCH_INVITATION", 
    MATCH_INVITATION_CANCELED  = "MATCH_INVITATION_CANCELED", 
    MATCH_STARTED  = "MATCH_STARTED",
    TEAM_INVITATION = "TEAM_INVITATION",  
    MATCH_ENDED = "MATCH_ENDED",
    MATCH_COMPLETED = "MATCH_COMPLETED",  
    SUBMISSION_RECEIVED = "SUBMISSION_RECEIVED", 
    SUBMISSION_RESULT = "SUBMISSION_RESULT", 
    OPPONENT_RESIGNED = "OPPONENT_RESIGNED", 
    FRIEND_REQUEST = "FRIEND_REQUEST", 
    FRIEND_ACCEPTED = "FRIEND_ACCEPTED"
}
  