package com.clashcode.backend.enums;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    MATCH_INVITATION,
    MATCH_STARTED,
    SUBMISSION_RECEIVED,
    SUBMISSION_RESULT,
    MATCH_COMPLETED,
    USER_RESIGNED,
}