-- Flyway migration: Insert test case files
-- Auto-generated from Clash-Code-File-Sys.rar
SET @BASE_PATH = '${BASE_PATH}';

INSERT INTO test_case_files (problem_id, test_case_id, file_type, content, file_path) VALUES
                                                                                          (1, 1, 'input', '5 3', CONCAT(@BASE_PATH,'/1/testcase_1_input.txt')),
                                                                                          (1, 1, 'output', '8', CONCAT(@BASE_PATH,'/1/testcase_1_output.txt')),
                                                                                          (1, 2, 'input', '10 20', CONCAT(@BASE_PATH,'/1/testcase_2_input.txt')),
                                                                                          (1, 2, 'output', '30', CONCAT(@BASE_PATH,'/1/testcase_2_output.txt')),
                                                                                          (1, 3, 'input', '-5 5', CONCAT(@BASE_PATH,'/1/testcase_3_input.txt')),
                                                                                          (1, 3, 'output', '0', CONCAT(@BASE_PATH,'/1/testcase_3_output.txt')),
                                                                                          (1, 4, 'input', '100 200', CONCAT(@BASE_PATH,'/1/testcase_4_input.txt')),
                                                                                          (1, 4, 'output', '300', CONCAT(@BASE_PATH,'/1/testcase_4_output.txt')),
                                                                                          (1, 5, 'input', '0 0', CONCAT(@BASE_PATH,'/1/testcase_5_input.txt')),
                                                                                          (1, 5, 'output', '0', CONCAT(@BASE_PATH,'/1/testcase_5_output.txt')),
                                                                                          (2, 6, 'input', '5 3 7', CONCAT(@BASE_PATH,'/2/testcase_6_input.txt')),
                                                                                          (2, 6, 'output', '7', CONCAT(@BASE_PATH,'/2/testcase_6_output.txt')),
                                                                                          (2, 7, 'input', '10 20 15', CONCAT(@BASE_PATH,'/2/testcase_7_input.txt')),
                                                                                          (2, 7, 'output', '20', CONCAT(@BASE_PATH,'/2/testcase_7_output.txt')),
                                                                                          (2, 8, 'input', '-5 -10 -3', CONCAT(@BASE_PATH,'/2/testcase_8_input.txt')),
                                                                                          (2, 8, 'output', '-3', CONCAT(@BASE_PATH,'/2/testcase_8_output.txt')),
                                                                                          (2, 9, 'input', '100 100 100', CONCAT(@BASE_PATH,'/2/testcase_9_input.txt')),
                                                                                          (2, 9, 'output', '100', CONCAT(@BASE_PATH,'/2/testcase_9_output.txt')),
                                                                                          (2, 10, 'input', '0 -5 5', CONCAT(@BASE_PATH,'/2/testcase_10_input.txt')),
                                                                                          (2, 10, 'output', '5', CONCAT(@BASE_PATH,'/2/testcase_10_output.txt')),
                                                                                          (3, 11, 'input', '4', CONCAT(@BASE_PATH,'/3/testcase_11_input.txt')),
                                                                                          (3, 11, 'output', 'Even', CONCAT(@BASE_PATH,'/3/testcase_11_output.txt')),
                                                                                          (3, 12, 'input', '7', CONCAT(@BASE_PATH,'/3/testcase_12_input.txt')),
                                                                                          (3, 12, 'output', 'Odd', CONCAT(@BASE_PATH,'/3/testcase_12_output.txt')),
                                                                                          (3, 13, 'input', '0', CONCAT(@BASE_PATH,'/3/testcase_13_input.txt')),
                                                                                          (3, 13, 'output', 'Even', CONCAT(@BASE_PATH,'/3/testcase_13_output.txt')),
                                                                                          (3, 14, 'input', '100', CONCAT(@BASE_PATH,'/3/testcase_14_input.txt')),
                                                                                          (3, 14, 'output', 'Even', CONCAT(@BASE_PATH,'/3/testcase_14_output.txt')),
                                                                                          (3, 15, 'input', '999', CONCAT(@BASE_PATH,'/3/testcase_15_input.txt')),
                                                                                          (3, 15, 'output', 'Odd', CONCAT(@BASE_PATH,'/3/testcase_15_output.txt')),
                                                                                          (4, 16, 'input', '5
1 2 3 4 5', CONCAT(@BASE_PATH,'/4/testcase_16_input.txt')),
                                                                                          (4, 16, 'output', '15', CONCAT(@BASE_PATH,'/4/testcase_16_output.txt')),
                                                                                          (4, 17, 'input', '3
10 20 30', CONCAT(@BASE_PATH,'/4/testcase_17_input.txt')),
                                                                                          (4, 17, 'output', '60', CONCAT(@BASE_PATH,'/4/testcase_17_output.txt')),
                                                                                          (4, 18, 'input', '4
-5 5 -10 10', CONCAT(@BASE_PATH,'/4/testcase_18_input.txt')),
                                                                                          (4, 18, 'output', '0', CONCAT(@BASE_PATH,'/4/testcase_18_output.txt')),
                                                                                          (4, 19, 'input', '6
1 1 1 1 1 1', CONCAT(@BASE_PATH,'/4/testcase_19_input.txt')),
                                                                                          (4, 19, 'output', '6', CONCAT(@BASE_PATH,'/4/testcase_19_output.txt')),
                                                                                          (4, 20, 'input', '1
100', CONCAT(@BASE_PATH,'/4/testcase_20_input.txt')),
                                                                                          (4, 20, 'output', '100', CONCAT(@BASE_PATH,'/4/testcase_20_output.txt')),
                                                                                          (5, 101, 'input', '5', CONCAT(@BASE_PATH,'/5/testcase_101_input.txt')),
                                                                                          (6, 26, 'input', '12 8', CONCAT(@BASE_PATH,'/6/testcase_26_input.txt')),
                                                                                          (6, 26, 'output', '4', CONCAT(@BASE_PATH,'/6/testcase_26_output.txt')),
                                                                                          (6, 27, 'input', '15 25', CONCAT(@BASE_PATH,'/6/testcase_27_input.txt')),
                                                                                          (6, 27, 'output', '5', CONCAT(@BASE_PATH,'/6/testcase_27_output.txt')),
                                                                                          (6, 28, 'input', '7 13', CONCAT(@BASE_PATH,'/6/testcase_28_input.txt')),
                                                                                          (6, 28, 'output', '1', CONCAT(@BASE_PATH,'/6/testcase_28_output.txt')),
                                                                                          (6, 29, 'input', '100 50', CONCAT(@BASE_PATH,'/6/testcase_29_input.txt')),
                                                                                          (6, 29, 'output', '50', CONCAT(@BASE_PATH,'/6/testcase_29_output.txt')),
                                                                                          (6, 30, 'input', '48 18', CONCAT(@BASE_PATH,'/6/testcase_30_input.txt')),
                                                                                          (6, 30, 'output', '6', CONCAT(@BASE_PATH,'/6/testcase_30_output.txt')),
                                                                                          (7, 31, 'input', 'hello', CONCAT(@BASE_PATH,'/7/testcase_31_input.txt')),
                                                                                          (7, 31, 'output', '2', CONCAT(@BASE_PATH,'/7/testcase_31_output.txt')),
                                                                                          (7, 32, 'input', 'AEIOU', CONCAT(@BASE_PATH,'/7/testcase_32_input.txt')),
                                                                                          (7, 32, 'output', '5', CONCAT(@BASE_PATH,'/7/testcase_32_output.txt')),
                                                                                          (7, 33, 'input', 'programming', CONCAT(@BASE_PATH,'/7/testcase_33_input.txt')),
                                                                                          (7, 33, 'output', '3', CONCAT(@BASE_PATH,'/7/testcase_33_output.txt')),
                                                                                          (7, 34, 'input', 'xyz', CONCAT(@BASE_PATH,'/7/testcase_34_input.txt')),
                                                                                          (7, 34, 'output', '0', CONCAT(@BASE_PATH,'/7/testcase_34_output.txt')),
                                                                                          (7, 35, 'input', 'Beautiful', CONCAT(@BASE_PATH,'/7/testcase_35_input.txt')),
                                                                                          (7, 35, 'output', '5', CONCAT(@BASE_PATH,'/7/testcase_35_output.txt')),
                                                                                          (8, 36, 'input', 'hello', CONCAT(@BASE_PATH,'/8/testcase_36_input.txt')),
                                                                                          (8, 36, 'output', 'olleh', CONCAT(@BASE_PATH,'/8/testcase_36_output.txt')),
                                                                                          (8, 37, 'input', 'world', CONCAT(@BASE_PATH,'/8/testcase_37_input.txt')),
                                                                                          (8, 37, 'output', 'dlrow', CONCAT(@BASE_PATH,'/8/testcase_37_output.txt')),
                                                                                          (8, 38, 'input', 'racecar', CONCAT(@BASE_PATH,'/8/testcase_38_input.txt')),
                                                                                          (8, 38, 'output', 'racecar', CONCAT(@BASE_PATH,'/8/testcase_38_output.txt')),
                                                                                          (8, 39, 'input', '12345', CONCAT(@BASE_PATH,'/8/testcase_39_input.txt')),
                                                                                          (8, 39, 'output', '54321', CONCAT(@BASE_PATH,'/8/testcase_39_output.txt')),
                                                                                          (8, 40, 'input', 'a', CONCAT(@BASE_PATH,'/8/testcase_40_input.txt')),
                                                                                          (8, 40, 'output', 'a', CONCAT(@BASE_PATH,'/8/testcase_40_output.txt')),
                                                                                          (9, 41, 'input', '123', CONCAT(@BASE_PATH,'/9/testcase_41_input.txt')),
                                                                                          (9, 41, 'output', '6', CONCAT(@BASE_PATH,'/9/testcase_41_output.txt')),
                                                                                          (9, 42, 'input', '999', CONCAT(@BASE_PATH,'/9/testcase_42_input.txt')),
                                                                                          (9, 42, 'output', '27', CONCAT(@BASE_PATH,'/9/testcase_42_output.txt')),
                                                                                          (9, 43, 'input', '1000', CONCAT(@BASE_PATH,'/9/testcase_43_input.txt')),
                                                                                          (9, 43, 'output', '1', CONCAT(@BASE_PATH,'/9/testcase_43_output.txt')),
                                                                                          (9, 44, 'input', '5555', CONCAT(@BASE_PATH,'/9/testcase_44_input.txt')),
                                                                                          (9, 44, 'output', '20', CONCAT(@BASE_PATH,'/9/testcase_44_output.txt')),
                                                                                          (9, 45, 'input', '0', CONCAT(@BASE_PATH,'/9/testcase_45_input.txt')),
                                                                                          (9, 45, 'output', '0', CONCAT(@BASE_PATH,'/9/testcase_45_output.txt')),
                                                                                          (10, 46, 'input', 'racecar', CONCAT(@BASE_PATH,'/10/testcase_46_input.txt')),
                                                                                          (10, 46, 'output', 'Yes', CONCAT(@BASE_PATH,'/10/testcase_46_output.txt')),
                                                                                          (10, 47, 'input', 'hello', CONCAT(@BASE_PATH,'/10/testcase_47_input.txt')),
                                                                                          (10, 47, 'output', 'No', CONCAT(@BASE_PATH,'/10/testcase_47_output.txt')),
                                                                                          (10, 48, 'input', 'madam', CONCAT(@BASE_PATH,'/10/testcase_48_input.txt')),
                                                                                          (10, 48, 'output', 'Yes', CONCAT(@BASE_PATH,'/10/testcase_48_output.txt')),
                                                                                          (10, 49, 'input', '12321', CONCAT(@BASE_PATH,'/10/testcase_49_input.txt')),
                                                                                          (10, 49, 'output', 'Yes', CONCAT(@BASE_PATH,'/10/testcase_49_output.txt')),
                                                                                          (10, 50, 'input', 'abcd', CONCAT(@BASE_PATH,'/10/testcase_50_input.txt')),
                                                                                          (10, 50, 'output', 'No', CONCAT(@BASE_PATH,'/10/testcase_50_output.txt')),
                                                                                          (11, 51, 'input', '5
2 4 6 8 10', CONCAT(@BASE_PATH,'/11/testcase_51_input.txt')),
                                                                                          (11, 51, 'output', '30', CONCAT(@BASE_PATH,'/11/testcase_51_output.txt')),
                                                                                          (11, 52, 'input', '3
100 200 300', CONCAT(@BASE_PATH,'/11/testcase_52_input.txt')),
                                                                                          (11, 52, 'output', '600', CONCAT(@BASE_PATH,'/11/testcase_52_output.txt')),
                                                                                          (11, 53, 'input', '4
-1 -2 -3 -4', CONCAT(@BASE_PATH,'/11/testcase_53_input.txt')),
                                                                                          (11, 53, 'output', '-10', CONCAT(@BASE_PATH,'/11/testcase_53_output.txt')),
                                                                                          (11, 54, 'input', '2
50 50', CONCAT(@BASE_PATH,'/11/testcase_54_input.txt')),
                                                                                          (11, 54, 'output', '100', CONCAT(@BASE_PATH,'/11/testcase_54_output.txt')),
                                                                                          (11, 55, 'input', '1
7', CONCAT(@BASE_PATH,'/11/testcase_55_input.txt')),
                                                                                          (11, 55, 'output', '7', CONCAT(@BASE_PATH,'/11/testcase_55_output.txt')),
                                                                                          (12, 56, 'input', '5
1 5 3 9 2', CONCAT(@BASE_PATH,'/12/testcase_56_input.txt')),
                                                                                          (12, 56, 'output', '9', CONCAT(@BASE_PATH,'/12/testcase_56_output.txt')),
                                                                                          (12, 57, 'input', '3
100 200 150', CONCAT(@BASE_PATH,'/12/testcase_57_input.txt')),
                                                                                          (12, 57, 'output', '200', CONCAT(@BASE_PATH,'/12/testcase_57_output.txt')),
                                                                                          (12, 58, 'input', '4
-1 -5 -3 -2', CONCAT(@BASE_PATH,'/12/testcase_58_input.txt')),
                                                                                          (12, 58, 'output', '-1', CONCAT(@BASE_PATH,'/12/testcase_58_output.txt')),
                                                                                          (12, 59, 'input', '6
7 7 7 7 7 7', CONCAT(@BASE_PATH,'/12/testcase_59_input.txt')),
                                                                                          (12, 59, 'output', '7', CONCAT(@BASE_PATH,'/12/testcase_59_output.txt')),
                                                                                          (12, 60, 'input', '1
42', CONCAT(@BASE_PATH,'/12/testcase_60_input.txt')),
                                                                                          (12, 60, 'output', '42', CONCAT(@BASE_PATH,'/12/testcase_60_output.txt')),
                                                                                          (13, 61, 'input', '5
1 2 3 4 5', CONCAT(@BASE_PATH,'/13/testcase_61_input.txt')),
                                                                                          (13, 61, 'output', '2', CONCAT(@BASE_PATH,'/13/testcase_61_output.txt')),
                                                                                          (13, 62, 'input', '4
2 4 6 8', CONCAT(@BASE_PATH,'/13/testcase_62_input.txt')),
                                                                                          (13, 62, 'output', '4', CONCAT(@BASE_PATH,'/13/testcase_62_output.txt')),
                                                                                          (13, 63, 'input', '3
1 3 5', CONCAT(@BASE_PATH,'/13/testcase_63_input.txt')),
                                                                                          (13, 63, 'output', '0', CONCAT(@BASE_PATH,'/13/testcase_63_output.txt')),
                                                                                          (13, 64, 'input', '6
10 15 20 25 30 35', CONCAT(@BASE_PATH,'/13/testcase_64_input.txt')),
                                                                                          (13, 64, 'output', '3', CONCAT(@BASE_PATH,'/13/testcase_64_output.txt')),
                                                                                          (13, 65, 'input', '1
7', CONCAT(@BASE_PATH,'/13/testcase_65_input.txt')),
                                                                                          (13, 65, 'output', '0', CONCAT(@BASE_PATH,'/13/testcase_65_output.txt')),
                                                                                          (14, 66, 'input', '4', CONCAT(@BASE_PATH,'/14/testcase_66_input.txt')),
                                                                                          (14, 66, 'output', '24', CONCAT(@BASE_PATH,'/14/testcase_66_output.txt')),
                                                                                          (14, 67, 'input', '6', CONCAT(@BASE_PATH,'/14/testcase_67_input.txt')),
                                                                                          (14, 67, 'output', '720', CONCAT(@BASE_PATH,'/14/testcase_67_output.txt')),
                                                                                          (14, 68, 'input', '0', CONCAT(@BASE_PATH,'/14/testcase_68_input.txt')),
                                                                                          (14, 68, 'output', '1', CONCAT(@BASE_PATH,'/14/testcase_68_output.txt')),
                                                                                          (14, 69, 'input', '3', CONCAT(@BASE_PATH,'/14/testcase_69_input.txt')),
                                                                                          (14, 69, 'output', '6', CONCAT(@BASE_PATH,'/14/testcase_69_output.txt')),
                                                                                          (14, 70, 'input', '8', CONCAT(@BASE_PATH,'/14/testcase_70_input.txt')),
                                                                                          (14, 70, 'output', '40320', CONCAT(@BASE_PATH,'/14/testcase_70_output.txt')),
                                                                                          (15, 71, 'input', '0', CONCAT(@BASE_PATH,'/15/testcase_71_input.txt')),
                                                                                          (15, 71, 'output', '0', CONCAT(@BASE_PATH,'/15/testcase_71_output.txt')),
                                                                                          (15, 72, 'input', '1', CONCAT(@BASE_PATH,'/15/testcase_72_input.txt')),
                                                                                          (15, 72, 'output', '1', CONCAT(@BASE_PATH,'/15/testcase_72_output.txt')),
                                                                                          (15, 73, 'input', '5', CONCAT(@BASE_PATH,'/15/testcase_73_input.txt')),
                                                                                          (15, 73, 'output', '5', CONCAT(@BASE_PATH,'/15/testcase_73_output.txt')),
                                                                                          (15, 74, 'input', '10', CONCAT(@BASE_PATH,'/15/testcase_74_input.txt')),
                                                                                          (15, 74, 'output', '55', CONCAT(@BASE_PATH,'/15/testcase_74_output.txt')),
                                                                                          (15, 75, 'input', '15', CONCAT(@BASE_PATH,'/15/testcase_75_input.txt')),
                                                                                          (15, 75, 'output', '610', CONCAT(@BASE_PATH,'/15/testcase_75_output.txt')),
                                                                                          (16, 76, 'input', '7', CONCAT(@BASE_PATH,'/16/testcase_76_input.txt')),
                                                                                          (16, 76, 'output', 'Yes', CONCAT(@BASE_PATH,'/16/testcase_76_output.txt')),
                                                                                          (16, 77, 'input', '10', CONCAT(@BASE_PATH,'/16/testcase_77_input.txt')),
                                                                                          (16, 77, 'output', 'No', CONCAT(@BASE_PATH,'/16/testcase_77_output.txt')),
                                                                                          (16, 78, 'input', '2', CONCAT(@BASE_PATH,'/16/testcase_78_input.txt')),
                                                                                          (16, 78, 'output', 'Yes', CONCAT(@BASE_PATH,'/16/testcase_78_output.txt')),
                                                                                          (16, 79, 'input', '1', CONCAT(@BASE_PATH,'/16/testcase_79_input.txt')),
                                                                                          (16, 79, 'output', 'No', CONCAT(@BASE_PATH,'/16/testcase_79_output.txt')),
                                                                                          (16, 80, 'input', '29', CONCAT(@BASE_PATH,'/16/testcase_80_input.txt')),
                                                                                          (16, 80, 'output', 'Yes', CONCAT(@BASE_PATH,'/16/testcase_80_output.txt')),
                                                                                          (17, 81, 'input', '123', CONCAT(@BASE_PATH,'/17/testcase_81_input.txt')),
                                                                                          (17, 81, 'output', '321', CONCAT(@BASE_PATH,'/17/testcase_81_output.txt')),
                                                                                          (17, 82, 'input', '500', CONCAT(@BASE_PATH,'/17/testcase_82_input.txt')),
                                                                                          (17, 82, 'output', '5', CONCAT(@BASE_PATH,'/17/testcase_82_output.txt')),
                                                                                          (17, 83, 'input', '1000', CONCAT(@BASE_PATH,'/17/testcase_83_input.txt')),
                                                                                          (17, 83, 'output', '1', CONCAT(@BASE_PATH,'/17/testcase_83_output.txt')),
                                                                                          (17, 84, 'input', '9876', CONCAT(@BASE_PATH,'/17/testcase_84_input.txt')),
                                                                                          (17, 84, 'output', '6789', CONCAT(@BASE_PATH,'/17/testcase_84_output.txt')),
                                                                                          (17, 85, 'input', '1', CONCAT(@BASE_PATH,'/17/testcase_85_input.txt')),
                                                                                          (17, 85, 'output', '1', CONCAT(@BASE_PATH,'/17/testcase_85_output.txt')),
                                                                                          (18, 86, 'input', 'hello world', CONCAT(@BASE_PATH,'/18/testcase_86_input.txt')),
                                                                                          (18, 86, 'output', '2', CONCAT(@BASE_PATH,'/18/testcase_86_output.txt')),
                                                                                          (18, 87, 'input', 'this is a test', CONCAT(@BASE_PATH,'/18/testcase_87_input.txt')),
                                                                                          (18, 87, 'output', '4', CONCAT(@BASE_PATH,'/18/testcase_87_output.txt')),
                                                                                          (18, 88, 'input', 'one', CONCAT(@BASE_PATH,'/18/testcase_88_input.txt')),
                                                                                          (18, 88, 'output', '1', CONCAT(@BASE_PATH,'/18/testcase_88_output.txt')),
                                                                                          (18, 89, 'input', 'count the words here please', CONCAT(@BASE_PATH,'/18/testcase_89_input.txt')),
                                                                                          (18, 89, 'output', '5', CONCAT(@BASE_PATH,'/18/testcase_89_output.txt')),
                                                                                          (18, 90, 'input', 'a b c d e', CONCAT(@BASE_PATH,'/18/testcase_90_input.txt')),
                                                                                          (18, 90, 'output', '5', CONCAT(@BASE_PATH,'/18/testcase_90_output.txt')),
                                                                                          (19, 91, 'input', '3
1 2 3', CONCAT(@BASE_PATH,'/19/testcase_91_input.txt')),
                                                                                          (19, 91, 'output', '14', CONCAT(@BASE_PATH,'/19/testcase_91_output.txt')),
                                                                                          (19, 92, 'input', '4
2 2 2 2', CONCAT(@BASE_PATH,'/19/testcase_92_input.txt')),
                                                                                          (19, 92, 'output', '16', CONCAT(@BASE_PATH,'/19/testcase_92_output.txt')),
                                                                                          (19, 93, 'input', '5
1 1 1 1 1', CONCAT(@BASE_PATH,'/19/testcase_93_input.txt')),
                                                                                          (19, 93, 'output', '5', CONCAT(@BASE_PATH,'/19/testcase_93_output.txt')),
                                                                                          (19, 94, 'input', '2
5 5', CONCAT(@BASE_PATH,'/19/testcase_94_input.txt')),
                                                                                          (19, 94, 'output', '50', CONCAT(@BASE_PATH,'/19/testcase_94_output.txt')),
                                                                                          (19, 95, 'input', '3
3 4 5', CONCAT(@BASE_PATH,'/19/testcase_95_input.txt')),
                                                                                          (19, 95, 'output', '50', CONCAT(@BASE_PATH,'/19/testcase_95_output.txt')),
                                                                                          (20, 96, 'input', '5
1 2 3 4 5', CONCAT(@BASE_PATH,'/20/testcase_96_input.txt')),
                                                                                          (20, 96, 'output', '3', CONCAT(@BASE_PATH,'/20/testcase_96_output.txt')),
                                                                                          (20, 97, 'input', '4
2 4 6 8', CONCAT(@BASE_PATH,'/20/testcase_97_input.txt')),
                                                                                          (20, 97, 'output', '0', CONCAT(@BASE_PATH,'/20/testcase_97_output.txt')),
                                                                                          (20, 98, 'input', '3
1 3 5', CONCAT(@BASE_PATH,'/20/testcase_98_input.txt')),
                                                                                          (20, 98, 'output', '3', CONCAT(@BASE_PATH,'/20/testcase_98_output.txt')),
                                                                                          (20, 99, 'input', '6
10 15 20 25 30 35', CONCAT(@BASE_PATH,'/20/testcase_99_input.txt')),
                                                                                          (20, 99, 'output', '3', CONCAT(@BASE_PATH,'/20/testcase_99_output.txt')),
                                                                                          (20, 100, 'input', '1
7', CONCAT(@BASE_PATH,'/20/testcase_100_input.txt')),
                                                                                          (20, 100, 'output', '1', CONCAT(@BASE_PATH,'/20/testcase_100_output.txt'));