spring.application.name=matching-service
spring.output.ansi.enabled=ALWAYS

# Redis
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.username=${REDISUSER}
spring.data.redis.password=${REDISPASSWORD}
spring.data.redis.url=${REDIS_URL}
spring.data.redis.timeout=2000


backend.url=${BACKEND_URL:http://localhost:8080}

# Server port
server.port=${PORT}
